-- Limpar questoes antigas de teste
DELETE FROM questoes WHERE id LIKE 'q_%';

-- Inserir questoes novas
INSERT INTO questoes (id, pergunta, alternativas, correta, disciplina, banca, concurso, ano, comentario, dificuldade) VALUES

-- PORTUGUES (15 questoes)
('q_port_001', 'Assinale a alternativa em que a concordancia nominal esta CORRETA:', $$["E necessario paciencia.", "E necessaria a paciencia.", "E necessario a paciencia.", "Sao necessario paciencia."]$$, 1, 'Portugues', 'CESPE', 'INSS', 2024, 'Concordancia correta com artigo.', 'medio'),
('q_port_002', 'Em qual frase a crase esta empregada CORRETAMENTE?', $$["Vou a pe.", "Refiro-me a pessoa que chegou.", "Chegamos a duas horas.", "Comprei a vista."]$$, 1, 'Portugues', 'FCC', 'TRT', 2024, 'Crase correta: preposicao a + artigo a.', 'medio'),
('q_port_003', 'Quanto a colocacao pronominal, esta CORRETA:', $$["Me disseram que voce viajou.", "Nunca te enganei.", "Aqui trabalha-se muito.", "Tudo se resolve."]$$, 3, 'Portugues', 'VUNESP', 'Prefeitura', 2024, 'Palavra atrativa exige proclise.', 'dificil'),
('q_port_004', 'Funcao sintatica de AO DIRETOR:', $$["Objeto direto", "Objeto indireto", "Complemento nominal", "Adjunto adverbial"]$$, 1, 'Portugues', 'CESPE', 'BB', 2024, 'Objeto indireto com preposicao.', 'medio'),
('q_port_005', 'Qual apresenta voz passiva analitica?', $$["Venderam-se produtos.", "Os produtos foram vendidos.", "Precisa-se de ajuda.", "Vendem-se casas."]$$, 1, 'Portugues', 'FGV', 'Camara', 2024, 'Auxiliar + participio.', 'medio'),
('q_port_006', 'Assinale a alternativa com ERRO de regencia:', $$["Assisti ao filme.", "Prefiro cafe do que cha.", "Esqueci-me do compromisso.", "Simpatizei com ela."]$$, 1, 'Portugues', 'FCC', 'TJ-SP', 2024, 'Preferir exige A a B.', 'dificil'),
('q_port_007', 'Pronome relativo INCORRETO:', $$["A casa onde moro.", "O livro cujas paginas rasgaram.", "A pessoa que chegou.", "O filme que assisti."]$$, 3, 'Portugues', 'CESPE', 'CGU', 2024, 'Assistir exige preposicao.', 'dificil'),
('q_port_008', 'Uso CORRETO de mau:', $$["Ele e um mau aluno.", "Ele passou mau.", "O mau tempo.", "Todos os mau exemplos."]$$, 0, 'Portugues', 'FCC', 'TRT', 2024, 'Mau e adjetivo.', 'facil'),
('q_port_009', 'Figura de linguagem em A vida e uma caixa de surpresas:', $$["Metafora", "Comparacao", "Metonimia", "Personificacao"]$$, 0, 'Portugues', 'VUNESP', 'SEDUC', 2024, 'Metafora e comparacao implicita.', 'facil'),
('q_port_010', 'Pronome de tratamento para Prefeito:', $$["Vossa Excelencia", "Vossa Senhoria", "Vossa Magnificencia", "Vossa Eminencia"]$$, 0, 'Portugues', 'CESPE', 'Prefeitura', 2024, 'Prefeitos usam Vossa Excelencia.', 'facil'),
('q_port_011', 'ERRO de pontuacao em:', $$["Estudei, porem nao passei.", "Estudei; no entanto, nao passei.", "Estudei, no entanto nao passei.", "Estudei. No entanto, passei."]$$, 2, 'Portugues', 'FGV', 'TJ-RJ', 2024, 'Conjuncao deslocada pede virgulas.', 'medio'),
('q_port_012', 'Quantos nucleos tem o objeto direto em Comprei DOIS LIVROS E TRES CADERNOS?', $$["Um", "Dois", "Tres", "Nenhum"]$$, 1, 'Portugues', 'CESPE', 'INSS', 2024, 'Objeto direto composto.', 'facil'),
('q_port_013', 'Oracao subordinada substantiva objetiva direta:', $$["E importante que voce estude.", "Espero que voce passe.", "Tenho certeza de que vai dar certo.", "A verdade e que ele mentiu."]$$, 1, 'Portugues', 'FCC', 'TCE', 2024, 'E objeto direto do verbo esperar.', 'dificil'),
('q_port_014', 'Uso correto de onde:', $$["Esse e o momento onde tudo mudou.", "A cidade onde nasci.", "O dia onde te conheci.", "A razao onde ele foi."]$$, 1, 'Portugues', 'VUNESP', 'TJ-SP', 2024, 'Onde indica lugar fisico.', 'medio'),
('q_port_015', 'Palavra INCORRETAMENTE grafada:', $$["Excecao", "Assessoria", "Privilegio", "Excessao"]$$, 3, 'Portugues', 'CESPE', 'TRE', 2024, 'O correto e excecao.', 'facil'),

-- MATEMATICA (15 questoes)
('q_mat_001', 'Preco de R$ 200 com aumento de 15%:', $$["R$ 215", "R$ 230", "R$ 225", "R$ 220"]$$, 1, 'Matematica', 'CESPE', 'BB', 2024, '200 x 1,15 = 230.', 'facil'),
('q_mat_002', 'R$ 500 com desconto de 20%:', $$["R$ 450", "R$ 400", "R$ 480", "R$ 420"]$$, 1, 'Matematica', 'FCC', 'TRT', 2024, '500 x 0,80 = 400.', 'facil'),
('q_mat_003', '25% de 840:', $$["200", "210", "220", "180"]$$, 1, 'Matematica', 'VUNESP', 'Prefeitura', 2024, '840 dividido 4 = 210.', 'facil'),
('q_mat_004', 'Salario de R$ 3.000 com aumento de 8%:', $$["R$ 3.180", "R$ 3.240", "R$ 3.200", "R$ 3.280"]$$, 1, 'Matematica', 'CESPE', 'TCU', 2024, '3000 x 1,08 = 3240.', 'facil'),
('q_mat_005', '5 funcionarios fazem em 12 dias. Quantos dias para 3 funcionarios?', $$["15 dias", "20 dias", "18 dias", "24 dias"]$$, 1, 'Matematica', 'FCC', 'TJ-SP', 2024, 'Inversa: 5x12=60, 60/3=20.', 'medio'),
('q_mat_006', 'Torneira A enche em 6h, B em 3h. Juntas:', $$["1,5h", "2h", "2,5h", "4,5h"]$$, 1, 'Matematica', 'CESPE', 'PF', 2024, '1/6 + 1/3 = 1/2 por hora = 2h.', 'medio'),
('q_mat_007', 'Triplo de um numero menos 15 e 45. O numero e:', $$["15", "20", "25", "30"]$$, 1, 'Matematica', 'FGV', 'TJ-RJ', 2024, '3x-15=45, x=20.', 'facil'),
('q_mat_008', 'Media de 5 numeros e 18. Retirando 8, nova media:', $$["20", "20,5", "19", "21"]$$, 0, 'Matematica', 'CESPE', 'INSS', 2024, 'Soma 90, retira 8: 82/4=20,5.', 'medio'),
('q_mat_009', '60% sao homens. 80 homens = quantos no total?', $$["120", "133", "140", "150"]$$, 1, 'Matematica', 'FCC', 'TRE', 2024, '60%=80, 100%=133.', 'medio'),
('q_mat_010', 'R$ 10.000 a 2% ao mes por 6 meses (juros simples):', $$["R$ 1.000", "R$ 1.200", "R$ 1.500", "R$ 2.000"]$$, 1, 'Matematica', 'CESPE', 'BB', 2024, 'J=10000x0,02x6=1200.', 'facil'),
('q_mat_011', '3/5 de um numero e 45. O numero e:', $$["60", "75", "90", "105"]$$, 1, 'Matematica', 'VUNESP', 'TCM', 2024, '45x5/3=75.', 'facil'),
('q_mat_012', 'Area de retangulo 8cm x 5cm:', $$["13 cm2", "26 cm2", "40 cm2", "80 cm2"]$$, 2, 'Matematica', 'CESPE', 'TRT', 2024, '8x5=40.', 'facil'),
('q_mat_013', '8 horas/dia. Quantos dias para 120 horas?', $$["12", "15", "18", "20"]$$, 1, 'Matematica', 'FCC', 'SABESP', 2024, '120/8=15.', 'facil'),
('q_mat_014', 'Se 2x+5=19, x e:', $$["5", "6", "7", "8"]$$, 2, 'Matematica', 'CESPE', 'PRF', 2024, '2x=14, x=7.', 'facil'),
('q_mat_015', 'Quantos minutos em 2,5 horas?', $$["120", "130", "150", "180"]$$, 2, 'Matematica', 'FGV', 'Camara', 2024, '2,5x60=150.', 'facil'),

-- INFORMATICA (15 questoes)
('q_info_001', 'Tecla de atalho para copiar:', $$["Ctrl+V", "Ctrl+C", "Ctrl+X", "Ctrl+Z"]$$, 1, 'Informatica', 'CESPE', 'TRE', 2024, 'Ctrl+C copia.', 'facil'),
('q_info_002', 'Negrito no Word:', $$["Ctrl+I", "Ctrl+B", "Ctrl+U", "Ctrl+N"]$$, 1, 'Informatica', 'FCC', 'TRT', 2024, 'Ctrl+B = Bold.', 'facil'),
('q_info_003', 'Extensao de arquivo compactado:', $$[".doc", ".zip", ".exe", ".pdf"]$$, 1, 'Informatica', 'VUNESP', 'Prefeitura', 2024, '.zip e compactado.', 'facil'),
('q_info_004', 'O que e navegador?', $$["Antivirus", "Programa para acessar sites", "Sistema operacional", "Firewall"]$$, 1, 'Informatica', 'CESPE', 'BB', 2024, 'Chrome, Firefox, Edge.', 'facil'),
('q_info_005', 'Funcao para media no Excel:', $$["=SOMA()", "=MEDIA()", "=CONT()", "=SE()"]$$, 1, 'Informatica', 'FCC', 'TCE', 2024, '=MEDIA() calcula media.', 'facil'),
('q_info_006', 'Protocolo para ENVIAR emails:', $$["HTTP", "FTP", "SMTP", "POP3"]$$, 2, 'Informatica', 'CESPE', 'TRF', 2024, 'SMTP envia, POP3 recebe.', 'medio'),
('q_info_007', 'HTTP significa:', $$["HyperText Transfer Protocol", "High Transfer Text", "HyperText Transmission", "High Text Transfer"]$$, 0, 'Informatica', 'FGV', 'Camara', 2024, 'Protocolo de transferencia.', 'facil'),
('q_info_008', 'Tecla para atualizar pagina:', $$["F1", "F5", "F12", "F4"]$$, 1, 'Informatica', 'VUNESP', 'SEDUC', 2024, 'F5 atualiza.', 'facil'),
('q_info_009', 'O que e firewall?', $$["Backup", "Barreira de seguranca de rede", "Antivirus", "Editor"]$$, 1, 'Informatica', 'CESPE', 'PF', 2024, 'Controla trafego de rede.', 'medio'),
('q_info_010', 'Selecionar tudo:', $$["Ctrl+S", "Ctrl+A", "Ctrl+T", "Ctrl+E"]$$, 1, 'Informatica', 'FCC', 'TJ-SP', 2024, 'Ctrl+A = All.', 'facil'),
('q_info_011', 'DNS serve para:', $$["Enviar emails", "Traduzir nomes em IPs", "Proteger virus", "Backup"]$$, 1, 'Informatica', 'CESPE', 'TCU', 2024, 'Traduz dominio em IP.', 'medio'),
('q_info_012', 'Cloud computing e:', $$["Antivirus", "Armazenamento remoto via internet", "Navegador", "Sistema operacional"]$$, 1, 'Informatica', 'FGV', 'TJ-RJ', 2024, 'Nuvem: Google Drive.', 'facil'),
('q_info_013', 'Diferenca RAM e HD:', $$["Nao ha", "RAM temporaria, HD permanente", "RAM permanente, HD temporaria", "Ambos temporarios"]$$, 1, 'Informatica', 'CESPE', 'INSS', 2024, 'RAM rapida/temporaria.', 'medio'),
('q_info_014', 'O que e phishing?', $$["Virus", "Fraude para roubo de dados", "Editor", "Firewall"]$$, 1, 'Informatica', 'CESPE', 'PF', 2024, 'Engenharia social.', 'medio'),
('q_info_015', 'Onde ficam arquivos excluidos?', $$["Documentos", "Lixeira", "Desktop", "Downloads"]$$, 1, 'Informatica', 'CESPE', 'TRE', 2024, 'Lixeira armazena temporariamente.', 'facil'),

-- DIREITO CONSTITUCIONAL (15 questoes)
('q_const_001', 'Todo poder emana:', $$["Do Presidente", "Do povo", "Do Congresso", "Dos Ministros"]$$, 1, 'Direito Constitucional', 'CESPE', 'TRF', 2024, 'Art. 1 paragrafo unico CF/88.', 'facil'),
('q_const_002', 'Poderes da Uniao:', $$["Executivo e Legislativo", "Executivo, Legislativo e Judiciario", "Legislativo e Judiciario", "Executivo e Judiciario"]$$, 1, 'Direito Constitucional', 'FCC', 'TRT', 2024, 'Art. 2 CF/88.', 'facil'),
('q_const_003', 'Mandato presidencial:', $$["3 anos", "4 anos", "5 anos", "6 anos"]$$, 1, 'Direito Constitucional', 'CESPE', 'PF', 2024, 'Art. 82: 4 anos.', 'facil'),
('q_const_004', 'Senadores por Estado:', $$["2", "3", "4", "Varia"]$$, 1, 'Direito Constitucional', 'FGV', 'OAB', 2024, 'Art. 46: 3 senadores.', 'facil'),
('q_const_005', 'Direitos fundamentais estao no Titulo:', $$["I", "II", "III", "IV"]$$, 1, 'Direito Constitucional', 'CESPE', 'TCU', 2024, 'Titulo II.', 'medio'),
('q_const_006', 'Remedio para direito liquido e certo:', $$["HC", "Mandado de Seguranca", "HD", "Acao Popular"]$$, 1, 'Direito Constitucional', 'FCC', 'TJ-SP', 2024, 'MS protege direito liquido.', 'medio'),
('q_const_007', 'Saude e direito de:', $$["Quem paga", "Todos", "Trabalhadores", "Idosos"]$$, 1, 'Direito Constitucional', 'CESPE', 'SUS', 2024, 'Art. 196: direito de todos.', 'facil'),
('q_const_008', 'Principio da legalidade:', $$["Ninguem obrigado senao por lei", "Todos iguais", "Lei retroage", "Juiz cria leis"]$$, 0, 'Direito Constitucional', 'FCC', 'TRE', 2024, 'Art. 5, II.', 'facil'),
('q_const_009', 'Entrada em domicilio sem consentimento:', $$["Dia/noite com ordem", "Flagrante a qualquer hora", "So de dia", "Nunca"]$$, 1, 'Direito Constitucional', 'CESPE', 'PRF', 2024, 'Art. 5, XI.', 'medio'),
('q_const_010', 'Idade minima para Presidente:', $$["21", "25", "30", "35"]$$, 3, 'Direito Constitucional', 'FGV', 'OAB', 2024, 'Art. 14: 35 anos.', 'facil'),
('q_const_011', 'Voto no Brasil:', $$["Obrigatorio todos", "Facultativo todos", "Obrigatorio 18-70", "So homens"]$$, 2, 'Direito Constitucional', 'CESPE', 'TRE', 2024, 'Art. 14.', 'medio'),
('q_const_012', 'Deputados Federais:', $$["513", "594", "81", "243"]$$, 0, 'Direito Constitucional', 'FCC', 'TRT', 2024, 'Art. 45: 513.', 'medio'),
('q_const_013', 'Julga Presidente por crime de responsabilidade:', $$["STF", "Senado", "Camara", "TSE"]$$, 1, 'Direito Constitucional', 'CESPE', 'AGU', 2024, 'Art. 52.', 'medio'),
('q_const_014', 'HC protege:', $$["Expressao", "Locomocao", "Imprensa", "Religiao"]$$, 1, 'Direito Constitucional', 'CESPE', 'DPE', 2024, 'Liberdade ir/vir.', 'facil'),
('q_const_015', 'STF tem quantos Ministros:', $$["9", "11", "13", "15"]$$, 1, 'Direito Constitucional', 'FGV', 'OAB', 2024, 'Art. 101: 11.', 'facil'),

-- DIREITO ADMINISTRATIVO (15 questoes)  
('q_adm_001', 'Principios da Administracao Publica:', $$["LIMPE", "Apenas Legalidade", "LMP", "LIFE"]$$, 0, 'Direito Administrativo', 'CESPE', 'TCU', 2024, 'Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiencia.', 'facil'),
('q_adm_002', 'Supremacia do interesse publico:', $$["Publico prevalece", "Privado prevalece", "Sao iguais", "Nao ha"]$$, 0, 'Direito Administrativo', 'FCC', 'TRT', 2024, 'Interesse coletivo acima.', 'facil'),
('q_adm_003', 'Poder de policia e:', $$["Punir servidores", "Limitar direitos pelo interesse publico", "Legislar", "Julgar"]$$, 1, 'Direito Administrativo', 'CESPE', 'PF', 2024, 'Condicionar uso.', 'medio'),
('q_adm_004', 'Investidura depende de:', $$["Indicacao", "Concurso publico", "Vontade", "Taxa"]$$, 1, 'Direito Administrativo', 'FCC', 'TJ-SP', 2024, 'Art. 37, II.', 'facil'),
('q_adm_005', 'Estabilidade apos:', $$["1 ano", "2 anos", "3 anos", "5 anos"]$$, 2, 'Direito Administrativo', 'CESPE', 'TRE', 2024, 'Art. 41: 3 anos.', 'facil'),
('q_adm_006', 'Revogacao atinge ato:', $$["Legal e oportuno", "Ilegal", "Inconstitucional", "Nulo"]$$, 0, 'Direito Administrativo', 'FGV', 'TCM', 2024, 'Revoga ato legal.', 'medio'),
('q_adm_007', 'Licitacao obrigatoria para:', $$["So compras grandes", "Obras, servicos, compras", "So obras", "Nao obrigatoria"]$$, 1, 'Direito Administrativo', 'CESPE', 'CGU', 2024, 'Art. 37, XXI.', 'facil'),
('q_adm_008', 'Modalidade para obras de grande vulto:', $$["Convite", "Tomada de Precos", "Concorrencia", "Pregao"]$$, 2, 'Direito Administrativo', 'FCC', 'TRF', 2024, 'Concorrencia: grandes valores.', 'medio'),
('q_adm_009', 'Acumular 2 cargos:', $$["Nunca", "Se houver compatibilidade", "Sempre", "So com autorizacao"]$$, 1, 'Direito Administrativo', 'CESPE', 'INSS', 2024, 'Art. 37, XVI.', 'medio'),
('q_adm_010', 'Autotutela significa:', $$["Administracao reve atos", "So Judiciario anula", "Nao pode anular", "Nao reve"]$$, 0, 'Direito Administrativo', 'FCC', 'TCE', 2024, 'Sumula 473 STF.', 'medio'),
('q_adm_011', 'Prescricao disciplinar:', $$["2 anos", "3 anos", "5 anos", "10 anos"]$$, 2, 'Direito Administrativo', 'CESPE', 'TRF', 2024, 'Lei 8.112/90: 5 anos.', 'dificil'),
('q_adm_012', 'Desapropriacao pode ser por:', $$["So necessidade", "Necessidade, utilidade ou interesse social", "Nao precisa indenizacao", "So Presidente"]$$, 1, 'Direito Administrativo', 'FCC', 'TJ-PE', 2024, 'Tres hipoteses.', 'medio'),
('q_adm_013', 'Concessao de servico e:', $$["Transferencia definitiva", "Delegacao temporaria", "Venda", "Extincao"]$$, 1, 'Direito Administrativo', 'CESPE', 'ANAC', 2024, 'Delegacao contratual.', 'medio'),
('q_adm_014', 'Responsabilidade do Estado:', $$["Subjetiva", "Objetiva", "Nao existe", "So por dolo"]$$, 1, 'Direito Administrativo', 'CESPE', 'AGU', 2024, 'Art. 37 paragrafo 6.', 'medio'),
('q_adm_015', 'Controle externo por:', $$["Propria Administracao", "Congresso com TCU", "So TCU", "So Presidente"]$$, 1, 'Direito Administrativo', 'FCC', 'TCU', 2024, 'Art. 71.', 'medio'),

-- DIREITO PENAL (15 questoes)
('q_penal_001', 'Crime consumado quando:', $$["Ha intencao", "Reune todos elementos", "E descoberto", "Autor preso"]$$, 1, 'Direito Penal', 'CESPE', 'PF', 2024, 'Art. 14, I CP.', 'facil'),
('q_penal_002', 'Legitima defesa exclui:', $$["So pena", "Ilicitude", "So prisao", "Nada"]$$, 1, 'Direito Penal', 'FCC', 'TJ-SP', 2024, 'Art. 23 CP.', 'medio'),
('q_penal_003', 'Imputabilidade penal:', $$["16 anos", "18 anos", "21 anos", "14 anos"]$$, 1, 'Direito Penal', 'CESPE', 'PRF', 2024, 'Art. 228 CF.', 'facil'),
('q_penal_004', 'Roubo difere de furto por:', $$["Violencia ou grave ameaca", "Valor", "Ser de dia", "Lugar"]$$, 0, 'Direito Penal', 'FGV', 'OAB', 2024, 'Art. 157 CP.', 'facil'),
('q_penal_005', 'Dolo e quando agente:', $$["Age com culpa", "Quer resultado ou assume risco", "Age sem intencao", "Desconhece lei"]$$, 1, 'Direito Penal', 'CESPE', 'PC-DF', 2024, 'Art. 18, I CP.', 'medio'),
('q_penal_006', 'Pena perpetua no Brasil:', $$["Sim", "Nao, vedada", "So hediondos", "So terrorismo"]$$, 1, 'Direito Penal', 'FCC', 'TRT', 2024, 'Art. 5 CF.', 'facil'),
('q_penal_007', 'Pena maxima no CP:', $$["20 anos", "30 anos", "40 anos", "Perpetua"]$$, 2, 'Direito Penal', 'CESPE', 'AGU', 2024, 'Art. 75 CP.', 'medio'),
('q_penal_008', 'Erro de tipo exclui:', $$["So pena", "Dolo", "Culpabilidade", "Nada"]$$, 1, 'Direito Penal', 'FCC', 'DPE', 2024, 'Art. 20 CP.', 'dificil'),
('q_penal_009', 'Crimes hediondos sao:', $$["Inafiancaveis", "Afiancaveis", "Prescritos em 5 anos", "So multa"]$$, 0, 'Direito Penal', 'CESPE', 'PF', 2024, 'Art. 5 CF.', 'medio'),
('q_penal_010', 'Homicidio qualificado:', $$["6-20 anos", "12-30 anos", "2-6 anos", "1-3 anos"]$$, 1, 'Direito Penal', 'CESPE', 'PC-SP', 2024, 'Art. 121 paragrafo 2.', 'medio'),
('q_penal_011', 'Peculato e praticado por:', $$["Qualquer pessoa", "Funcionario publico", "So politicos", "So juizes"]$$, 1, 'Direito Penal', 'FCC', 'TCE', 2024, 'Art. 312 CP.', 'medio'),
('q_penal_012', 'Pena da tentativa:', $$["Igual consumado", "Reduzida 1/3 a 2/3", "Nao punivel", "Aumentada"]$$, 1, 'Direito Penal', 'CESPE', 'PRF', 2024, 'Art. 14 CP.', 'facil'),
('q_penal_013', 'Crime impossivel ocorre quando:', $$["Meio ineficaz ou objeto inexistente", "Ha tentativa", "Ha consumacao", "E descoberto"]$$, 0, 'Direito Penal', 'FCC', 'DPE', 2024, 'Art. 17 CP.', 'medio'),
('q_penal_014', 'Embriaguez voluntaria:', $$["Exclui crime", "Nao exclui imputabilidade", "Reduz pena", "Exclui culpabilidade"]$$, 1, 'Direito Penal', 'FCC', 'TJ-SP', 2024, 'Art. 28 CP.', 'medio'),
('q_penal_015', 'Extincao da punibilidade por:', $$["So perdao", "Morte, prescricao, anistia etc", "So prescricao", "Nao extingue"]$$, 1, 'Direito Penal', 'FCC', 'TJ-PE', 2024, 'Art. 107 CP.', 'medio'),

-- RACIOCINIO LOGICO (15 questoes)
('q_raciocinio_001', 'Se Todos os gatos sao mamiferos e Todos os mamiferos sao animais, entao:', $$["Todos os animais sao gatos", "Todos os gatos sao animais", "Alguns animais nao sao gatos", "Nenhuma correta"]$$, 1, 'Raciocinio Logico', 'CESPE', 'TCU', 2024, 'Silogismo.', 'medio'),
('q_raciocinio_002', 'A negacao de Todos os brasileiros sao altos e:', $$["Nenhum brasileiro e alto", "Alguns brasileiros nao sao altos", "Todos sao baixos", "Alguns sao altos"]$$, 1, 'Raciocinio Logico', 'FCC', 'TRT', 2024, 'Negacao de todo.', 'medio'),
('q_raciocinio_003', 'Na sequencia 2, 5, 8, 11, proximo numero:', $$["13", "14", "15", "16"]$$, 1, 'Raciocinio Logico', 'VUNESP', 'Prefeitura', 2024, 'PA razao 3.', 'facil'),
('q_raciocinio_004', 'Se p implica q e verdadeiro e p e verdadeiro, entao q e:', $$["Falso", "Verdadeiro", "Qualquer valor", "Indeterminado"]$$, 1, 'Raciocinio Logico', 'CESPE', 'Receita', 2024, 'Modus Ponens.', 'medio'),
('q_raciocinio_005', 'A negacao de p E q e:', $$["NAO p E NAO q", "NAO p OU NAO q", "p OU q", "NAO (p OU q)"]$$, 1, 'Raciocinio Logico', 'FCC', 'TRF', 2024, 'Lei de De Morgan.', 'medio'),
('q_raciocinio_006', 'Urna com 3 bolas vermelhas e 2 azuis. Probabilidade de tirar vermelha:', $$["2/5", "3/5", "1/2", "3/2"]$$, 1, 'Raciocinio Logico', 'CESPE', 'BB', 2024, 'Probabilidade = 3/5.', 'facil'),
('q_raciocinio_007', 'Se p OU q e falso, entao:', $$["p e q sao falsos", "p e q sao verdadeiros", "p falso q verdadeiro", "p verdadeiro"]$$, 0, 'Raciocinio Logico', 'FGV', 'TCM', 2024, 'Ambos devem ser falsos.', 'facil'),
('q_raciocinio_008', 'Comissoes de 3 pessoas com 5 pessoas:', $$["10", "15", "20", "60"]$$, 0, 'Raciocinio Logico', 'CESPE', 'INSS', 2024, 'Combinacao C(5,3)=10.', 'medio'),
('q_raciocinio_009', 'Hoje e terca. Que dia sera daqui a 100 dias?', $$["Segunda", "Terca", "Quarta", "Quinta"]$$, 2, 'Raciocinio Logico', 'FCC', 'TRE', 2024, '100/7 = 14 resto 2. Terca+2=Quinta.', 'medio'),
('q_raciocinio_010', 'A proposicao Se chove, entao rua molha e equivalente a:', $$["Se nao molha, entao nao chove", "Se molha, entao chove", "Nao equivalentes", "Chove e nao molha"]$$, 0, 'Raciocinio Logico', 'CESPE', 'PRF', 2024, 'Contrapositiva.', 'dificil'),
('q_raciocinio_011', 'Relogio adianta 5 min/dia. Em quantos dias adianta 1 hora?', $$["10 dias", "12 dias", "15 dias", "20 dias"]$$, 1, 'Raciocinio Logico', 'FCC', 'TCE', 2024, '60/5=12.', 'facil'),
('q_raciocinio_012', 'Sequencia de Fibonacci 1,1,2,3,5,8, proximo:', $$["11", "13", "15", "10"]$$, 1, 'Raciocinio Logico', 'CESPE', 'BB', 2024, '5+8=13.', 'facil'),
('q_raciocinio_013', 'Se Alguns politicos sao honestos e verdadeiro, entao:', $$["Todos sao", "Existe pelo menos um honesto", "Nenhum e", "Todos desonestos"]$$, 1, 'Raciocinio Logico', 'FCC', 'TRT', 2024, 'Alguns = pelo menos um.', 'facil'),
('q_raciocinio_014', 'Anagramas de ANA:', $$["3", "6", "2", "1"]$$, 0, 'Raciocinio Logico', 'CESPE', 'INSS', 2024, '3!/2!=3.', 'medio'),
('q_raciocinio_015', '30 pessoas, 18 ingles, 15 espanhol. Quantas falam ambos?', $$["3", "5", "10", "15"]$$, 0, 'Raciocinio Logico', 'FGV', 'TCM', 2024, '18+15-x=30, x=3.', 'medio');
