// Questões iniciais - 100+ questões para todas as bancas e matérias
const BANCAS = ['CESPE/CEBRASPE', 'FCC', 'VUNESP', 'FGV', 'IBFC', 'CESGRANRIO'];
const MATERIAS = ['Português', 'Matemática', 'Direito Constitucional', 'Direito Administrativo', 'Informática', 'Raciocínio Lógico'];

export const QUESTOES_INICIAIS = [
  // ===================== PORTUGUÊS =====================
  // CESPE
  { id: '1', disciplina: 'Português', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Assinale a alternativa correta quanto à concordância verbal.', optionA: 'Fazem dois anos que ele partiu.', optionB: 'Faz dois anos que ele partiu.', optionC: 'Fazem dois ano que ele partiu.', optionD: 'Faz dois ano que ele partiu.', correctAnswer: 1, explanation: 'O verbo fazer, quando indica tempo, é impessoal.', audioComment: '/audio/comentario_1.mp3' },
  { id: '2', disciplina: 'Português', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Qual frase está correta?', optionA: 'Haviam muitas pessoas.', optionB: 'Havia muitas pessoas.', optionC: 'Haviam muita pessoa.', optionD: 'Havia muita pessoa.', correctAnswer: 1, explanation: 'Haver no sentido de existir é impessoal.', audioComment: '/audio/comentario_2.mp3' },
  { id: '3', disciplina: 'Português', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Indique a opção com erro de crase.', optionA: 'Fui à escola.', optionB: 'Voltei à casa.', optionC: 'Cheguei à tarde.', optionD: 'Saí à pé.', correctAnswer: 3, explanation: 'A pé não leva crase.', audioComment: '/audio/comentario_3.mp3' },
  // FCC
  { id: '4', disciplina: 'Português', concurso: 'Geral', banca: 'FCC', title: 'Qual é o plural de cidadão?', optionA: 'Cidadões', optionB: 'Cidadãos', optionC: 'Cidadães', optionD: 'Cidadans', correctAnswer: 1, explanation: 'O plural correto é cidadãos.', audioComment: '/audio/comentario_4.mp3' },
  { id: '5', disciplina: 'Português', concurso: 'Geral', banca: 'FCC', title: 'Marque a alternativa com regência verbal correta.', optionA: 'Prefiro sorvete do que bolo.', optionB: 'Prefiro sorvete a bolo.', optionC: 'Prefiro mais sorvete que bolo.', optionD: 'Prefiro sorvete mais que bolo.', correctAnswer: 1, explanation: 'Preferir exige a preposição a.', audioComment: '/audio/comentario_5.mp3' },
  { id: '6', disciplina: 'Português', concurso: 'Geral', banca: 'FCC', title: 'Identifique a frase com erro de ortografia.', optionA: 'Ele está em êxtase.', optionB: 'Compramos muita maisena.', optionC: 'A exceção confirma a regra.', optionD: 'Houve muita excessão.', correctAnswer: 3, explanation: 'O correto é exceção, sem ss.', audioComment: '/audio/comentario_6.mp3' },
  // VUNESP
  { id: '7', disciplina: 'Português', concurso: 'Geral', banca: 'VUNESP', title: 'Assinale a forma verbal correta.', optionA: 'Se ele ver o filme.', optionB: 'Se ele vir o filme.', optionC: 'Se ele vier o filme.', optionD: 'Se ele viesse o filme.', correctAnswer: 1, explanation: 'Vir é o futuro do subjuntivo de ver.', audioComment: '/audio/comentario_7.mp3' },
  { id: '8', disciplina: 'Português', concurso: 'Geral', banca: 'VUNESP', title: 'Qual palavra é acentuada corretamente?', optionA: 'Ítem', optionB: 'Item', optionC: 'Itém', optionD: 'Itèm', correctAnswer: 1, explanation: 'Item não leva acento.', audioComment: '/audio/comentario_8.mp3' },
  // FGV
  { id: '9', disciplina: 'Português', concurso: 'Geral', banca: 'FGV', title: 'Indique o uso correto do pronome.', optionA: 'Para mim fazer o trabalho.', optionB: 'Para eu fazer o trabalho.', optionC: 'Para mim fazendo o trabalho.', optionD: 'Para eu fazendo o trabalho.', correctAnswer: 1, explanation: 'Antes de verbo usa-se eu, não mim.', audioComment: '/audio/comentario_9.mp3' },
  { id: '10', disciplina: 'Português', concurso: 'Geral', banca: 'FGV', title: 'Qual frase está na voz passiva?', optionA: 'O gato comeu o rato.', optionB: 'O rato foi comido pelo gato.', optionC: 'O gato come ratos.', optionD: 'Gatos comem ratos.', correctAnswer: 1, explanation: 'Voz passiva: sujeito sofre a ação.', audioComment: '/audio/comentario_10.mp3' },
  // IBFC
  { id: '11', disciplina: 'Português', concurso: 'Geral', banca: 'IBFC', title: 'Assinale a alternativa com pontuação correta.', optionA: 'Maria, José e Pedro, foram ao parque.', optionB: 'Maria José e Pedro foram ao parque.', optionC: 'Maria, José e Pedro foram ao parque.', optionD: 'Maria José, e Pedro foram ao parque.', correctAnswer: 2, explanation: 'Não se separa sujeito do verbo por vírgula.', audioComment: '/audio/comentario_11.mp3' },
  { id: '12', disciplina: 'Português', concurso: 'Geral', banca: 'IBFC', title: 'Qual é o antônimo de "prolixo"?', optionA: 'Extenso', optionB: 'Conciso', optionC: 'Longo', optionD: 'Detalhado', correctAnswer: 1, explanation: 'Prolixo = extenso demais; antônimo = conciso.', audioComment: '/audio/comentario_12.mp3' },
  // CESGRANRIO
  { id: '13', disciplina: 'Português', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Identifique a figura de linguagem em "O sol sorria".', optionA: 'Metáfora', optionB: 'Prosopopeia', optionC: 'Hipérbole', optionD: 'Eufemismo', correctAnswer: 1, explanation: 'Prosopopeia: atribuir ações humanas a seres inanimados.', audioComment: '/audio/comentario_13.mp3' },
  { id: '14', disciplina: 'Português', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Qual alternativa apresenta um pleonasmo?', optionA: 'Subir para cima', optionB: 'Casa grande', optionC: 'Carro veloz', optionD: 'Livro antigo', correctAnswer: 0, explanation: 'Pleonasmo: redundância de ideias.', audioComment: '/audio/comentario_14.mp3' },
  { id: '15', disciplina: 'Português', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Qual a classe gramatical de "rapidamente"?', optionA: 'Adjetivo', optionB: 'Advérbio', optionC: 'Substantivo', optionD: 'Verbo', correctAnswer: 1, explanation: 'Palavras terminadas em -mente são advérbios de modo.', audioComment: '/audio/comentario_15.mp3' },
  { id: '16', disciplina: 'Português', concurso: 'Geral', banca: 'FCC', title: 'Identifique o sujeito da oração: "Choveu muito ontem."', optionA: 'Choveu', optionB: 'Muito', optionC: 'Ontem', optionD: 'Sujeito inexistente', correctAnswer: 3, explanation: 'Verbos de fenômenos da natureza são impessoais.', audioComment: '/audio/comentario_16.mp3' },
  { id: '17', disciplina: 'Português', concurso: 'Geral', banca: 'VUNESP', title: 'Qual a forma correta?', optionA: 'Menas pessoas', optionB: 'Menos pessoas', optionC: 'Meno pessoas', optionD: 'Menores pessoas', correctAnswer: 1, explanation: 'Menos é invariável.', audioComment: '/audio/comentario_17.mp3' },

  // ===================== MATEMÁTICA =====================
  // CESPE
  { id: '18', disciplina: 'Matemática', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Quanto é 15% de 200?', optionA: '25', optionB: '30', optionC: '35', optionD: '40', correctAnswer: 1, explanation: '200 × 0,15 = 30', audioComment: '/audio/comentario_18.mp3' },
  { id: '19', disciplina: 'Matemática', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Qual é a raiz quadrada de 144?', optionA: '10', optionB: '11', optionC: '12', optionD: '13', correctAnswer: 2, explanation: '12 × 12 = 144', audioComment: '/audio/comentario_19.mp3' },
  { id: '20', disciplina: 'Matemática', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: '2 + 2 × 3 = ?', optionA: '8', optionB: '10', optionC: '12', optionD: '6', correctAnswer: 0, explanation: 'Multiplicação primeiro: 2 + 6 = 8', audioComment: '/audio/comentario_20.mp3' },
  // FCC
  { id: '21', disciplina: 'Matemática', concurso: 'Geral', banca: 'FCC', title: 'Quanto é 1/4 + 1/4?', optionA: '1/2', optionB: '1/8', optionC: '2/4', optionD: '2/8', correctAnswer: 0, explanation: '1/4 + 1/4 = 2/4 = 1/2', audioComment: '/audio/comentario_21.mp3' },
  { id: '22', disciplina: 'Matemática', concurso: 'Geral', banca: 'FCC', title: '50% de 80 é:', optionA: '30', optionB: '35', optionC: '40', optionD: '45', correctAnswer: 2, explanation: '80 ÷ 2 = 40', audioComment: '/audio/comentario_22.mp3' },
  { id: '23', disciplina: 'Matemática', concurso: 'Geral', banca: 'FCC', title: 'Qual é o resultado de 3² + 4²?', optionA: '7', optionB: '12', optionC: '25', optionD: '49', correctAnswer: 2, explanation: '9 + 16 = 25', audioComment: '/audio/comentario_23.mp3' },
  // VUNESP
  { id: '24', disciplina: 'Matemática', concurso: 'Geral', banca: 'VUNESP', title: 'Se x + 5 = 12, quanto vale x?', optionA: '5', optionB: '7', optionC: '17', optionD: '6', correctAnswer: 1, explanation: 'x = 12 - 5 = 7', audioComment: '/audio/comentario_24.mp3' },
  { id: '25', disciplina: 'Matemática', concurso: 'Geral', banca: 'VUNESP', title: 'Qual é a área de um quadrado de lado 5?', optionA: '10', optionB: '20', optionC: '25', optionD: '30', correctAnswer: 2, explanation: 'Área = lado² = 5² = 25', audioComment: '/audio/comentario_25.mp3' },
  // FGV
  { id: '26', disciplina: 'Matemática', concurso: 'Geral', banca: 'FGV', title: 'Um produto custava R$ 100 e teve 20% de desconto. Qual o novo preço?', optionA: 'R$ 70', optionB: 'R$ 75', optionC: 'R$ 80', optionD: 'R$ 85', correctAnswer: 2, explanation: '100 - 20 = 80', audioComment: '/audio/comentario_26.mp3' },
  { id: '27', disciplina: 'Matemática', concurso: 'Geral', banca: 'FGV', title: 'Qual é o MMC entre 4 e 6?', optionA: '8', optionB: '10', optionC: '12', optionD: '24', correctAnswer: 2, explanation: 'MMC(4,6) = 12', audioComment: '/audio/comentario_27.mp3' },
  // IBFC
  { id: '28', disciplina: 'Matemática', concurso: 'Geral', banca: 'IBFC', title: 'Quantos minutos há em 2 horas?', optionA: '100', optionB: '120', optionC: '140', optionD: '180', correctAnswer: 1, explanation: '2 × 60 = 120 minutos', audioComment: '/audio/comentario_28.mp3' },
  { id: '29', disciplina: 'Matemática', concurso: 'Geral', banca: 'IBFC', title: 'Qual é 25% de 400?', optionA: '50', optionB: '75', optionC: '100', optionD: '125', correctAnswer: 2, explanation: '400 × 0,25 = 100', audioComment: '/audio/comentario_29.mp3' },
  // CESGRANRIO
  { id: '30', disciplina: 'Matemática', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Se 3x = 15, quanto vale x?', optionA: '3', optionB: '4', optionC: '5', optionD: '6', correctAnswer: 2, explanation: 'x = 15 ÷ 3 = 5', audioComment: '/audio/comentario_30.mp3' },
  { id: '31', disciplina: 'Matemática', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Qual é o perímetro de um retângulo 4x6?', optionA: '10', optionB: '20', optionC: '24', optionD: '30', correctAnswer: 1, explanation: 'Perímetro = 2×(4+6) = 20', audioComment: '/audio/comentario_31.mp3' },
  { id: '32', disciplina: 'Matemática', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Quanto é 0,5 × 0,5?', optionA: '0,10', optionB: '0,25', optionC: '0,50', optionD: '1,00', correctAnswer: 1, explanation: '0,5 × 0,5 = 0,25', audioComment: '/audio/comentario_32.mp3' },
  { id: '33', disciplina: 'Matemática', concurso: 'Geral', banca: 'FCC', title: 'Converta 3/4 em porcentagem.', optionA: '25%', optionB: '50%', optionC: '75%', optionD: '80%', correctAnswer: 2, explanation: '3/4 = 0,75 = 75%', audioComment: '/audio/comentario_33.mp3' },

  // ===================== DIREITO CONSTITUCIONAL =====================
  // CESPE
  { id: '34', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Quem promulga leis no Brasil?', optionA: 'Presidente', optionB: 'Congresso', optionC: 'STF', optionD: 'Senado', correctAnswer: 1, explanation: 'O Congresso Nacional promulga leis.', audioComment: '/audio/comentario_34.mp3' },
  { id: '35', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Quantos anos dura o mandato presidencial?', optionA: '2', optionB: '3', optionC: '4', optionD: '5', correctAnswer: 2, explanation: 'Mandato de 4 anos.', audioComment: '/audio/comentario_35.mp3' },
  { id: '36', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'A CF de 1988 tem quantos títulos?', optionA: '7', optionB: '8', optionC: '9', optionD: '10', correctAnswer: 2, explanation: 'São 9 títulos.', audioComment: '/audio/comentario_36.mp3' },
  // FCC
  { id: '37', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'FCC', title: 'Direitos fundamentais estão em qual artigo?', optionA: '1º', optionB: '3º', optionC: '5º', optionD: '7º', correctAnswer: 2, explanation: 'Art. 5º da CF/88.', audioComment: '/audio/comentario_37.mp3' },
  { id: '38', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'FCC', title: 'Qual poder julga?', optionA: 'Executivo', optionB: 'Legislativo', optionC: 'Judiciário', optionD: 'Moderador', correctAnswer: 2, explanation: 'Poder Judiciário julga.', audioComment: '/audio/comentario_38.mp3' },
  { id: '39', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'FCC', title: 'Quem é o chefe do Poder Executivo Federal?', optionA: 'Governador', optionB: 'Presidente', optionC: 'Prefeito', optionD: 'Ministro', correctAnswer: 1, explanation: 'O Presidente da República.', audioComment: '/audio/comentario_39.mp3' },
  // VUNESP
  { id: '40', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'VUNESP', title: 'Quantos senadores cada estado tem?', optionA: '1', optionB: '2', optionC: '3', optionD: '4', correctAnswer: 2, explanation: 'Cada estado tem 3 senadores.', audioComment: '/audio/comentario_40.mp3' },
  { id: '41', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'VUNESP', title: 'Qual é a idade mínima para ser deputado federal?', optionA: '18 anos', optionB: '21 anos', optionC: '25 anos', optionD: '30 anos', correctAnswer: 1, explanation: '21 anos para deputado federal.', audioComment: '/audio/comentario_41.mp3' },
  // FGV
  { id: '42', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'FGV', title: 'O voto no Brasil é obrigatório a partir de qual idade?', optionA: '16 anos', optionB: '18 anos', optionC: '21 anos', optionD: '25 anos', correctAnswer: 1, explanation: 'A partir de 18 anos o voto é obrigatório.', audioComment: '/audio/comentario_42.mp3' },
  { id: '43', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'FGV', title: 'Quem julga crimes comuns do Presidente?', optionA: 'STJ', optionB: 'STF', optionC: 'TSE', optionD: 'TST', correctAnswer: 1, explanation: 'O STF julga crimes comuns do Presidente.', audioComment: '/audio/comentario_43.mp3' },
  // IBFC
  { id: '44', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'IBFC', title: 'Cláusulas pétreas podem ser abolidas?', optionA: 'Sim, sempre', optionB: 'Não, nunca', optionC: 'Sim, por maioria simples', optionD: 'Sim, por unanimidade', correctAnswer: 1, explanation: 'Cláusulas pétreas não podem ser abolidas.', audioComment: '/audio/comentario_44.mp3' },
  { id: '45', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'IBFC', title: 'Qual o prazo do habeas corpus?', optionA: '24 horas', optionB: '48 horas', optionC: '72 horas', optionD: 'Imediato', correctAnswer: 3, explanation: 'Habeas corpus deve ter julgamento imediato.', audioComment: '/audio/comentario_45.mp3' },
  // CESGRANRIO
  { id: '46', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Qual é o quórum para aprovar PEC?', optionA: 'Maioria simples', optionB: 'Maioria absoluta', optionC: '3/5 dos membros', optionD: '2/3 dos membros', correctAnswer: 2, explanation: 'PEC exige 3/5 em dois turnos.', audioComment: '/audio/comentario_46.mp3' },
  { id: '47', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Quem julga crimes de responsabilidade do Presidente?', optionA: 'STF', optionB: 'Senado', optionC: 'Câmara', optionD: 'STJ', correctAnswer: 1, explanation: 'O Senado julga crimes de responsabilidade.', audioComment: '/audio/comentario_47.mp3' },
  { id: '48', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'A Constituição pode ser emendada durante intervenção federal?', optionA: 'Sim', optionB: 'Não', optionC: 'Só em casos urgentes', optionD: 'Só pelo STF', correctAnswer: 1, explanation: 'Não é permitido emendar a CF durante intervenção federal.', audioComment: '/audio/comentario_48.mp3' },
  { id: '49', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'FCC', title: 'Qual o número mínimo de deputados por estado?', optionA: '6', optionB: '8', optionC: '10', optionD: '12', correctAnswer: 1, explanation: 'Mínimo de 8 deputados por estado.', audioComment: '/audio/comentario_49.mp3' },

  // ===================== DIREITO ADMINISTRATIVO =====================
  // CESPE
  { id: '50', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Princípio da legalidade significa:', optionA: 'Fazer o que quiser', optionB: 'Só fazer o que a lei permite', optionC: 'Ignorar a lei', optionD: 'Criar leis', correctAnswer: 1, explanation: 'Administração só pode fazer o que a lei autoriza.', audioComment: '/audio/comentario_50.mp3' },
  { id: '51', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Ato administrativo pode ser:', optionA: 'Apenas verbal', optionB: 'Apenas escrito', optionC: 'Verbal ou escrito', optionD: 'Nunca escrito', correctAnswer: 2, explanation: 'Pode ser verbal ou escrito.', audioComment: '/audio/comentario_51.mp3' },
  { id: '52', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Servidor público pode acumular cargos?', optionA: 'Sempre', optionB: 'Nunca', optionC: 'Em casos permitidos', optionD: 'Apenas 3', correctAnswer: 2, explanation: 'Há casos permitidos na CF.', audioComment: '/audio/comentario_52.mp3' },
  // FCC
  { id: '53', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'FCC', title: 'Licitação serve para:', optionA: 'Contratar sem critério', optionB: 'Escolher a melhor proposta', optionC: 'Favorecer amigos', optionD: 'Gastar mais', correctAnswer: 1, explanation: 'Licitação busca a melhor proposta.', audioComment: '/audio/comentario_53.mp3' },
  { id: '54', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'FCC', title: 'Improbidade administrativa é:', optionA: 'Crime comum', optionB: 'Ato ilícito grave', optionC: 'Permitido', optionD: 'Opcional', correctAnswer: 1, explanation: 'É ato ilícito administrativo grave.', audioComment: '/audio/comentario_54.mp3' },
  { id: '55', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'FCC', title: 'Quais são os princípios do LIMPE?', optionA: 'Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência', optionB: 'Lei, Imparcialidade, Moral, Público, Eficaz', optionC: 'Legal, Impessoal, Moral, Público, Efetivo', optionD: 'Leal, Individual, Moroso, Privado, Econômico', correctAnswer: 0, explanation: 'LIMPE = Legalidade, Impessoalidade, Moralidade, Publicidade, Eficiência.', audioComment: '/audio/comentario_55.mp3' },
  // VUNESP
  { id: '56', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'VUNESP', title: 'Qual modalidade de licitação para menor valor?', optionA: 'Concurso', optionB: 'Leilão', optionC: 'Pregão', optionD: 'Convite', correctAnswer: 2, explanation: 'Pregão é para menor preço em bens e serviços comuns.', audioComment: '/audio/comentario_56.mp3' },
  { id: '57', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'VUNESP', title: 'Autarquia tem personalidade jurídica de:', optionA: 'Direito privado', optionB: 'Direito público', optionC: 'Mista', optionD: 'Não tem personalidade', correctAnswer: 1, explanation: 'Autarquias têm personalidade jurídica de direito público.', audioComment: '/audio/comentario_57.mp3' },
  // FGV
  { id: '58', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'FGV', title: 'O que é poder de polícia?', optionA: 'Poder da PM', optionB: 'Poder de fiscalizar e limitar direitos', optionC: 'Poder militar', optionD: 'Poder de prender', correctAnswer: 1, explanation: 'Poder de polícia = fiscalizar e limitar direitos em prol do interesse público.', audioComment: '/audio/comentario_58.mp3' },
  { id: '59', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'FGV', title: 'Qual prazo prescricional para ação de improbidade?', optionA: '3 anos', optionB: '5 anos', optionC: '8 anos', optionD: 'Imprescritível', correctAnswer: 2, explanation: 'Prescrição de 8 anos conforme a Lei 14.230/2021.', audioComment: '/audio/comentario_59.mp3' },
  // IBFC
  { id: '60', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'IBFC', title: 'Desapropriação é ato:', optionA: 'Discricionário', optionB: 'Vinculado', optionC: 'Facultativo', optionD: 'Ilegal', correctAnswer: 0, explanation: 'Desapropriação é ato discricionário quanto ao mérito.', audioComment: '/audio/comentario_60.mp3' },
  { id: '61', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'IBFC', title: 'Qual é o prazo do concurso público?', optionA: '1 ano', optionB: '2 anos, prorrogável por mais 2', optionC: '3 anos', optionD: '5 anos', correctAnswer: 1, explanation: 'Prazo de 2 anos, prorrogável uma vez por igual período.', audioComment: '/audio/comentario_61.mp3' },
  // CESGRANRIO
  { id: '62', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Empresa pública tem capital:', optionA: 'Privado', optionB: '100% público', optionC: 'Misto', optionD: 'Estrangeiro', correctAnswer: 1, explanation: 'Empresa pública tem 100% de capital público.', audioComment: '/audio/comentario_62.mp3' },
  { id: '63', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Qual ato não pode ser revogado?', optionA: 'Atos discricionários', optionB: 'Atos vinculados', optionC: 'Atos de gestão', optionD: 'Atos normativos', correctAnswer: 1, explanation: 'Atos vinculados não podem ser revogados, apenas anulados.', audioComment: '/audio/comentario_63.mp3' },
  { id: '64', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Concessão de serviço público exige:', optionA: 'Dispensa de licitação', optionB: 'Licitação na modalidade concorrência', optionC: 'Convite', optionD: 'Pregão', correctAnswer: 1, explanation: 'Concessão exige licitação por concorrência ou diálogo competitivo.', audioComment: '/audio/comentario_64.mp3' },
  { id: '65', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'FCC', title: 'Anulação de ato administrativo pode ser feita:', optionA: 'Só pelo Judiciário', optionB: 'Só pela Administração', optionC: 'Pelo Judiciário ou pela Administração', optionD: 'Pelo Legislativo', correctAnswer: 2, explanation: 'Anulação pode ser feita pela Administração (autotutela) ou pelo Judiciário.', audioComment: '/audio/comentario_65.mp3' },

  // ===================== INFORMÁTICA =====================
  // CESPE
  { id: '66', disciplina: 'Informática', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'O que é CPU?', optionA: 'Memória', optionB: 'Processador', optionC: 'HD', optionD: 'Monitor', correctAnswer: 1, explanation: 'CPU é o processador.', audioComment: '/audio/comentario_66.mp3' },
  { id: '67', disciplina: 'Informática', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'RAM é memória:', optionA: 'Permanente', optionB: 'Temporária', optionC: 'Lenta', optionD: 'Externa', correctAnswer: 1, explanation: 'RAM é memória temporária.', audioComment: '/audio/comentario_67.mp3' },
  { id: '68', disciplina: 'Informática', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Qual NÃO é sistema operacional?', optionA: 'Windows', optionB: 'Linux', optionC: 'Word', optionD: 'MacOS', correctAnswer: 2, explanation: 'Word é editor de texto.', audioComment: '/audio/comentario_68.mp3' },
  // FCC
  { id: '69', disciplina: 'Informática', concurso: 'Geral', banca: 'FCC', title: 'Extensão de arquivo de imagem:', optionA: '.doc', optionB: '.jpg', optionC: '.exe', optionD: '.txt', correctAnswer: 1, explanation: '.jpg é imagem.', audioComment: '/audio/comentario_69.mp3' },
  { id: '70', disciplina: 'Informática', concurso: 'Geral', banca: 'FCC', title: 'Ctrl+C faz:', optionA: 'Colar', optionB: 'Copiar', optionC: 'Recortar', optionD: 'Deletar', correctAnswer: 1, explanation: 'Ctrl+C copia.', audioComment: '/audio/comentario_70.mp3' },
  { id: '71', disciplina: 'Informática', concurso: 'Geral', banca: 'FCC', title: 'O que significa HTML?', optionA: 'HyperText Markup Language', optionB: 'High Tech Modern Language', optionC: 'Home Tool Markup Language', optionD: 'Hyperlink Text Mode Language', correctAnswer: 0, explanation: 'HTML = HyperText Markup Language.', audioComment: '/audio/comentario_71.mp3' },
  // VUNESP
  { id: '72', disciplina: 'Informática', concurso: 'Geral', banca: 'VUNESP', title: 'O que é firewall?', optionA: 'Antivírus', optionB: 'Sistema de proteção de rede', optionC: 'Navegador', optionD: 'Editor de texto', correctAnswer: 1, explanation: 'Firewall protege a rede de acessos não autorizados.', audioComment: '/audio/comentario_72.mp3' },
  { id: '73', disciplina: 'Informática', concurso: 'Geral', banca: 'VUNESP', title: 'Qual tecla de atalho para salvar?', optionA: 'Ctrl+A', optionB: 'Ctrl+S', optionC: 'Ctrl+P', optionD: 'Ctrl+O', correctAnswer: 1, explanation: 'Ctrl+S salva o documento.', audioComment: '/audio/comentario_73.mp3' },
  // FGV
  { id: '74', disciplina: 'Informática', concurso: 'Geral', banca: 'FGV', title: 'O que é phishing?', optionA: 'Vírus', optionB: 'Golpe para roubar dados', optionC: 'Tipo de firewall', optionD: 'Programa de edição', correctAnswer: 1, explanation: 'Phishing é golpe que tenta roubar informações pessoais.', audioComment: '/audio/comentario_74.mp3' },
  { id: '75', disciplina: 'Informática', concurso: 'Geral', banca: 'FGV', title: 'Qual é a função do DNS?', optionA: 'Armazenar dados', optionB: 'Traduzir nomes de domínio em IP', optionC: 'Proteger contra vírus', optionD: 'Conectar impressoras', correctAnswer: 1, explanation: 'DNS converte nomes de sites em endereços IP.', audioComment: '/audio/comentario_75.mp3' },
  // IBFC
  { id: '76', disciplina: 'Informática', concurso: 'Geral', banca: 'IBFC', title: 'Qual programa é um navegador?', optionA: 'Word', optionB: 'Excel', optionC: 'Chrome', optionD: 'Photoshop', correctAnswer: 2, explanation: 'Chrome é um navegador de internet.', audioComment: '/audio/comentario_76.mp3' },
  { id: '77', disciplina: 'Informática', concurso: 'Geral', banca: 'IBFC', title: 'O que significa URL?', optionA: 'Uniform Resource Locator', optionB: 'Universal Resource Link', optionC: 'United Registry Location', optionD: 'User Resource Library', correctAnswer: 0, explanation: 'URL = Uniform Resource Locator.', audioComment: '/audio/comentario_77.mp3' },
  // CESGRANRIO
  { id: '78', disciplina: 'Informática', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Qual é a função do SSD?', optionA: 'Processar dados', optionB: 'Armazenar dados permanentemente', optionC: 'Exibir imagens', optionD: 'Conectar à internet', correctAnswer: 1, explanation: 'SSD armazena dados de forma permanente.', audioComment: '/audio/comentario_78.mp3' },
  { id: '79', disciplina: 'Informática', concurso: 'Geral', banca: 'CESGRANRIO', title: 'O que é backup?', optionA: 'Deletar arquivos', optionB: 'Cópia de segurança', optionC: 'Formatar disco', optionD: 'Instalar programa', correctAnswer: 1, explanation: 'Backup é cópia de segurança dos dados.', audioComment: '/audio/comentario_79.mp3' },
  { id: '80', disciplina: 'Informática', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Qual protocolo é usado para email?', optionA: 'HTTP', optionB: 'FTP', optionC: 'SMTP', optionD: 'TCP', correctAnswer: 2, explanation: 'SMTP é o protocolo para envio de emails.', audioComment: '/audio/comentario_80.mp3' },
  { id: '81', disciplina: 'Informática', concurso: 'Geral', banca: 'FCC', title: 'O que é cloud computing?', optionA: 'Computação local', optionB: 'Computação em nuvem', optionC: 'Tipo de vírus', optionD: 'Sistema operacional', correctAnswer: 1, explanation: 'Cloud computing = serviços de computação na nuvem.', audioComment: '/audio/comentario_81.mp3' },

  // ===================== RACIOCÍNIO LÓGICO =====================
  // CESPE
  { id: '82', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Se A > B e B > C, então:', optionA: 'A < C', optionB: 'A > C', optionC: 'A = C', optionD: 'Impossível saber', correctAnswer: 1, explanation: 'Transitividade: A > C', audioComment: '/audio/comentario_82.mp3' },
  { id: '83', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Próximo número: 2, 4, 8, 16, ?', optionA: '20', optionB: '24', optionC: '32', optionD: '64', correctAnswer: 2, explanation: 'Multiplica por 2: 16×2=32', audioComment: '/audio/comentario_83.mp3' },
  { id: '84', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Todo A é B. Todo B é C. Logo:', optionA: 'Todo A é C', optionB: 'Todo C é A', optionC: 'Nenhum A é C', optionD: 'Alguns A são C', correctAnswer: 0, explanation: 'Silogismo: Todo A é C.', audioComment: '/audio/comentario_84.mp3' },
  // FCC
  { id: '85', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'FCC', title: 'Negação de "Todos são":', optionA: 'Nenhum é', optionB: 'Alguns não são', optionC: 'Todos não são', optionD: 'Nenhum não é', correctAnswer: 1, explanation: 'Negação de todo é algum não.', audioComment: '/audio/comentario_85.mp3' },
  { id: '86', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'FCC', title: 'Se hoje é segunda, que dia foi 3 dias atrás?', optionA: 'Quinta', optionB: 'Sexta', optionC: 'Sábado', optionD: 'Domingo', correctAnswer: 1, explanation: 'Segunda - 3 dias = Sexta.', audioComment: '/audio/comentario_86.mp3' },
  { id: '87', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'FCC', title: 'P → Q é equivalente a:', optionA: 'Q → P', optionB: '~P ∨ Q', optionC: 'P ∧ Q', optionD: '~Q → ~P', correctAnswer: 1, explanation: 'Condicional equivale a ~P ∨ Q.', audioComment: '/audio/comentario_87.mp3' },
  // VUNESP
  { id: '88', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'VUNESP', title: 'Se chove, então a rua fica molhada. A rua está seca. Logo:', optionA: 'Choveu', optionB: 'Não choveu', optionC: 'Pode ter chovido', optionD: 'A rua está molhada', correctAnswer: 1, explanation: 'Modus tollens: se consequente é falso, antecedente é falso.', audioComment: '/audio/comentario_88.mp3' },
  { id: '89', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'VUNESP', title: 'Qual sequência: 1, 1, 2, 3, 5, 8, ?', optionA: '10', optionB: '11', optionC: '12', optionD: '13', correctAnswer: 3, explanation: 'Fibonacci: 5+8=13.', audioComment: '/audio/comentario_89.mp3' },
  // FGV
  { id: '90', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'FGV', title: 'A negação de "P e Q" é:', optionA: '~P e ~Q', optionB: '~P ou ~Q', optionC: 'P ou Q', optionD: '~P e Q', correctAnswer: 1, explanation: 'De Morgan: ~(P∧Q) = ~P∨~Q.', audioComment: '/audio/comentario_90.mp3' },
  { id: '91', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'FGV', title: 'Quantas diagonais tem um hexágono?', optionA: '6', optionB: '7', optionC: '8', optionD: '9', correctAnswer: 3, explanation: 'D = n(n-3)/2 = 6×3/2 = 9.', audioComment: '/audio/comentario_91.mp3' },
  // IBFC
  { id: '92', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'IBFC', title: 'Se "todo cachorro late" é verdadeiro, então:', optionA: 'Alguns cachorros não latem', optionB: 'Nenhum cachorro late', optionC: 'Pelo menos um cachorro late', optionD: 'Cachorros não existem', correctAnswer: 2, explanation: 'Se todo late, então pelo menos um late.', audioComment: '/audio/comentario_92.mp3' },
  { id: '93', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'IBFC', title: 'Próximo: 3, 6, 12, 24, ?', optionA: '36', optionB: '42', optionC: '48', optionD: '30', correctAnswer: 2, explanation: 'Multiplica por 2: 24×2=48.', audioComment: '/audio/comentario_93.mp3' },
  // CESGRANRIO
  { id: '94', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Se P é verdadeiro e Q é falso, então P∨Q é:', optionA: 'Verdadeiro', optionB: 'Falso', optionC: 'Indeterminado', optionD: 'Nulo', correctAnswer: 0, explanation: 'OR é verdadeiro se pelo menos um for verdadeiro.', audioComment: '/audio/comentario_94.mp3' },
  { id: '95', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Contraposição de "Se A então B" é:', optionA: 'Se B então A', optionB: 'Se não A então não B', optionC: 'Se não B então não A', optionD: 'A e B', correctAnswer: 2, explanation: 'Contraposição: ~Q → ~P.', audioComment: '/audio/comentario_95.mp3' },
  { id: '96', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'De quantas formas 5 pessoas podem sentar em fila?', optionA: '25', optionB: '60', optionC: '120', optionD: '720', correctAnswer: 2, explanation: '5! = 120 formas.', audioComment: '/audio/comentario_96.mp3' },
  { id: '97', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'FCC', title: 'Bicondicional P↔Q é verdadeiro quando:', optionA: 'P e Q têm valores iguais', optionB: 'P e Q têm valores diferentes', optionC: 'Apenas P é verdadeiro', optionD: 'Apenas Q é verdadeiro', correctAnswer: 0, explanation: 'Bicondicional é verdadeiro quando P e Q têm mesmo valor.', audioComment: '/audio/comentario_97.mp3' },
  
  // QUESTÕES EXTRAS PARA COMPLETAR 100+
  { id: '98', disciplina: 'Português', concurso: 'Geral', banca: 'VUNESP', title: 'Qual a conjugação correta do verbo "intervir" no pretérito?', optionA: 'Eu intervi', optionB: 'Eu intervim', optionC: 'Eu interveni', optionD: 'Eu interviu', correctAnswer: 1, explanation: 'Intervir segue a conjugação de vir: intervim.', audioComment: '/audio/comentario_98.mp3' },
  { id: '99', disciplina: 'Matemática', concurso: 'Geral', banca: 'FGV', title: 'Qual é o valor de 2³?', optionA: '6', optionB: '8', optionC: '9', optionD: '12', correctAnswer: 1, explanation: '2³ = 2×2×2 = 8.', audioComment: '/audio/comentario_99.mp3' },
  { id: '100', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'IBFC', title: 'Qual é a forma de governo do Brasil?', optionA: 'Monarquia', optionB: 'República', optionC: 'Parlamentarismo', optionD: 'Teocracia', correctAnswer: 1, explanation: 'Brasil é uma República Federativa.', audioComment: '/audio/comentario_100.mp3' },
  { id: '101', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Qual é a diferença entre ato vinculado e discricionário?', optionA: 'Vinculado permite escolha, discricionário não', optionB: 'Discricionário permite escolha de mérito, vinculado não', optionC: 'São iguais', optionD: 'Ambos permitem total liberdade', correctAnswer: 1, explanation: 'Ato discricionário permite análise de conveniência e oportunidade.', audioComment: '/audio/comentario_101.mp3' },
  { id: '102', disciplina: 'Informática', concurso: 'Geral', banca: 'VUNESP', title: 'O que é ransomware?', optionA: 'Antivírus', optionB: 'Malware que sequestra dados', optionC: 'Sistema operacional', optionD: 'Tipo de hardware', correctAnswer: 1, explanation: 'Ransomware é malware que criptografa dados e exige resgate.', audioComment: '/audio/comentario_102.mp3' },
  { id: '103', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'FGV', title: 'Quantos anagramas da palavra PAI?', optionA: '3', optionB: '6', optionC: '9', optionD: '12', correctAnswer: 1, explanation: '3! = 6 anagramas.', audioComment: '/audio/comentario_103.mp3' },
  { id: '104', disciplina: 'Português', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Qual é o sujeito em "Vendem-se casas"?', optionA: 'Vendem', optionB: 'se', optionC: 'casas', optionD: 'Sujeito indeterminado', correctAnswer: 2, explanation: 'Voz passiva sintética: casas é o sujeito.', audioComment: '/audio/comentario_104.mp3' },
  { id: '105', disciplina: 'Matemática', concurso: 'Geral', banca: 'IBFC', title: 'Se x/4 = 8, quanto vale x?', optionA: '2', optionB: '12', optionC: '32', optionD: '64', correctAnswer: 2, explanation: 'x = 8 × 4 = 32.', audioComment: '/audio/comentario_105.mp3' },
  { id: '106', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'FCC', title: 'Quem pode propor ADI?', optionA: 'Qualquer cidadão', optionB: 'Apenas o Presidente', optionC: 'Legitimados do art. 103', optionD: 'Apenas partidos políticos', correctAnswer: 2, explanation: 'Art. 103 lista os legitimados para propor ADI.', audioComment: '/audio/comentario_106.mp3' },
  { id: '107', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'VUNESP', title: 'O que é decadência administrativa?', optionA: 'Perda de prazo para anular ato', optionB: 'Criação de ato', optionC: 'Revogação de ato', optionD: 'Confirmação de ato', correctAnswer: 0, explanation: 'Decadência é a perda do prazo para anular ato ilegal (5 anos).', audioComment: '/audio/comentario_107.mp3' },
  { id: '108', disciplina: 'Informática', concurso: 'Geral', banca: 'FGV', title: 'O que é VPN?', optionA: 'Tipo de vírus', optionB: 'Rede privada virtual', optionC: 'Programa de edição', optionD: 'Tipo de processador', correctAnswer: 1, explanation: 'VPN = Virtual Private Network, conexão segura.', audioComment: '/audio/comentario_108.mp3' },
  { id: '109', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Qual é a negação de "Pelo menos um é"?', optionA: 'Todos são', optionB: 'Nenhum é', optionC: 'Alguns são', optionD: 'Muitos são', correctAnswer: 1, explanation: 'Negação de "existe" é "para todo não".', audioComment: '/audio/comentario_109.mp3' },
  { id: '110', disciplina: 'Português', concurso: 'Geral', banca: 'IBFC', title: 'Qual é o coletivo de lobos?', optionA: 'Manada', optionB: 'Alcateia', optionC: 'Matilha', optionD: 'Bando', correctAnswer: 1, explanation: 'Alcateia é o coletivo de lobos.', audioComment: '/audio/comentario_110.mp3' },
  { id: '111', disciplina: 'Matemática', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Qual é o dobro de 2⁴?', optionA: '16', optionB: '32', optionC: '64', optionD: '128', correctAnswer: 1, explanation: '2⁴ = 16, dobro = 32.', audioComment: '/audio/comentario_111.mp3' },
  { id: '112', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Estado de sítio pode durar no máximo:', optionA: '15 dias', optionB: '30 dias, prorrogável', optionC: '90 dias', optionD: 'Indeterminado', correctAnswer: 1, explanation: 'Estado de sítio: 30 dias, prorrogáveis.', audioComment: '/audio/comentario_112.mp3' },
  { id: '113', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'FCC', title: 'Qual é o regime jurídico das fundações públicas?', optionA: 'Sempre público', optionB: 'Sempre privado', optionC: 'Pode ser público ou privado', optionD: 'Misto obrigatório', correctAnswer: 2, explanation: 'Fundações públicas podem ter regime público ou privado.', audioComment: '/audio/comentario_113.mp3' },
  { id: '114', disciplina: 'Informática', concurso: 'Geral', banca: 'IBFC', title: 'O que faz o Ctrl+Z?', optionA: 'Salvar', optionB: 'Desfazer', optionC: 'Refazer', optionD: 'Fechar', correctAnswer: 1, explanation: 'Ctrl+Z desfaz a última ação.', audioComment: '/audio/comentario_114.mp3' },
  { id: '115', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'VUNESP', title: 'Se P é falso e Q é verdadeiro, P→Q é:', optionA: 'Verdadeiro', optionB: 'Falso', optionC: 'Indeterminado', optionD: 'Nulo', correctAnswer: 0, explanation: 'Condicional com antecedente falso é sempre verdadeiro.', audioComment: '/audio/comentario_115.mp3' },
  { id: '116', disciplina: 'Português', concurso: 'Geral', banca: 'FGV', title: 'Qual palavra tem dígrafo?', optionA: 'Praia', optionB: 'Ninho', optionC: 'Troca', optionD: 'Plano', correctAnswer: 1, explanation: 'NH é dígrafo (duas letras, um som).', audioComment: '/audio/comentario_116.mp3' },
  { id: '117', disciplina: 'Matemática', concurso: 'Geral', banca: 'FCC', title: 'Quanto é 3! (fatorial)?', optionA: '3', optionB: '6', optionC: '9', optionD: '12', correctAnswer: 1, explanation: '3! = 3×2×1 = 6.', audioComment: '/audio/comentario_117.mp3' },
  { id: '118', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'VUNESP', title: 'Quem decreta intervenção federal?', optionA: 'Congresso', optionB: 'Presidente', optionC: 'STF', optionD: 'Governador', correctAnswer: 1, explanation: 'O Presidente decreta a intervenção federal.', audioComment: '/audio/comentario_118.mp3' },
  { id: '119', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'O que é terceirização na Administração?', optionA: 'Contratação de terceiros para atividade-meio', optionB: 'Demissão de servidores', optionC: 'Criação de autarquias', optionD: 'Privatização total', correctAnswer: 0, explanation: 'Terceirização: contratar terceiros para serviços de apoio.', audioComment: '/audio/comentario_119.mp3' },
  { id: '120', disciplina: 'Informática', concurso: 'Geral', banca: 'CESGRANRIO', title: 'O que é LAN?', optionA: 'Rede de longa distância', optionB: 'Rede local', optionC: 'Tipo de cabo', optionD: 'Sistema operacional', correctAnswer: 1, explanation: 'LAN = Local Area Network (rede local).', audioComment: '/audio/comentario_120.mp3' },
  { id: '121', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'FCC', title: 'Qual o número de combinações de 5 elementos tomados 2 a 2?', optionA: '5', optionB: '10', optionC: '15', optionD: '20', correctAnswer: 1, explanation: 'C(5,2) = 5!/(2!×3!) = 10.', audioComment: '/audio/comentario_121.mp3' },
  { id: '122', disciplina: 'Português', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'O que é um verbo transitivo direto?', optionA: 'Exige preposição', optionB: 'Não exige complemento', optionC: 'Exige objeto direto sem preposição', optionD: 'É sempre intransitivo', correctAnswer: 2, explanation: 'VTD exige objeto direto (sem preposição).', audioComment: '/audio/comentario_122.mp3' },
  { id: '123', disciplina: 'Matemática', concurso: 'Geral', banca: 'VUNESP', title: 'Qual é a hipotenusa de um triângulo retângulo com catetos 3 e 4?', optionA: '5', optionB: '6', optionC: '7', optionD: '8', correctAnswer: 0, explanation: 'Pitágoras: √(9+16) = √25 = 5.', audioComment: '/audio/comentario_123.mp3' },
  { id: '124', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'FGV', title: 'O Ministério Público atua em qual função?', optionA: 'Legislativa', optionB: 'Executiva', optionC: 'Essencial à justiça', optionD: 'Judiciária', correctAnswer: 2, explanation: 'MP é função essencial à justiça.', audioComment: '/audio/comentario_124.mp3' },
  { id: '125', disciplina: 'Direito Administrativo', concurso: 'Geral', banca: 'IBFC', title: 'O que é a Súmula Vinculante?', optionA: 'Lei ordinária', optionB: 'Decisão do STF com efeito vinculante', optionC: 'Ato administrativo', optionD: 'Decreto presidencial', correctAnswer: 1, explanation: 'Súmula Vinculante é editada pelo STF e vincula todos.', audioComment: '/audio/comentario_125.mp3' },
  { id: '126', disciplina: 'Informática', concurso: 'Geral', banca: 'FCC', title: 'O que é IP?', optionA: 'Tipo de arquivo', optionB: 'Endereço do computador na rede', optionC: 'Programa antivírus', optionD: 'Tipo de memória', correctAnswer: 1, explanation: 'IP = Internet Protocol, identificador na rede.', audioComment: '/audio/comentario_126.mp3' },
  { id: '127', disciplina: 'Raciocínio Lógico', concurso: 'Geral', banca: 'CESGRANRIO', title: 'Se 10% de X é 50, quanto é X?', optionA: '5', optionB: '50', optionC: '500', optionD: '5000', correctAnswer: 2, explanation: 'X = 50/0,10 = 500.', audioComment: '/audio/comentario_127.mp3' },
  { id: '128', disciplina: 'Português', concurso: 'Geral', banca: 'FCC', title: 'O que é uma oração subordinada?', optionA: 'Oração independente', optionB: 'Oração que depende de outra', optionC: 'Oração principal', optionD: 'Oração sem sujeito', correctAnswer: 1, explanation: 'Subordinada depende sintaticamente da principal.', audioComment: '/audio/comentario_128.mp3' },
  { id: '129', disciplina: 'Matemática', concurso: 'Geral', banca: 'IBFC', title: 'Qual o valor de |−7|?', optionA: '-7', optionB: '7', optionC: '0', optionD: '14', correctAnswer: 1, explanation: 'Módulo de -7 é 7 (valor absoluto).', audioComment: '/audio/comentario_129.mp3' },
  { id: '130', disciplina: 'Direito Constitucional', concurso: 'Geral', banca: 'CESPE/CEBRASPE', title: 'Qual a idade mínima para ser senador?', optionA: '21 anos', optionB: '25 anos', optionC: '30 anos', optionD: '35 anos', correctAnswer: 3, explanation: 'Senador: mínimo 35 anos.', audioComment: '/audio/comentario_130.mp3' },
];

export default QUESTOES_INICIAIS;
